CREATE TABLE PASSENGER(PASS_ID INT PRIMARY KEY NOT NULL,
BOOKING_ID INT,
RECORD_STATUS BIT DEFAULT 1,
PASS_NAME VARCHAR(100) NOT NULL,
AGE INT NOT NULL,
GENDER VARCHAR(50) NOT NULL,
BERTH VARCHAR(100) FOREIGN KEY(BERTH) REFERENCES BERTH(BERTHTYPE),
SENIOR_CITIZEN BIT DEFAULT 0,
NATIONALITY VARCHAR(100) FOREIGN KEY(NATIONALITY) REFERENCES NATIONALITY(NATION) ,
ID_CARD VARCHAR(100) NOT NULL FOREIGN KEY(ID_CARD) REFERENCES ID_CARD_TYPE(ID_CARD),
ID_NO VARCHAR(50) NOT NULL UNIQUE ,
CREATED_BY VARCHAR(50) DEFAULT 'AFREEN',
CREATED_DATETIME DATETIME DEFAULT GETDATE(),
MODIFIED_BY VARCHAR(50) NOT NULL DEFAULT 'ADMIN',
MODIFIED_DATETIME DATETIME NOT NULL DEFAULT GETDATE(),
ROWGUID VARCHAR(MAX) DEFAULT NEWID());

select * from PASSENGER;
insert into PASSENGER (PASS_ID,BOOKING_ID,PASS_NAME,AGE,GENDER,BERTH,SENIOR_CITIZEN,NATIONALITY,ID_CARD,ID_NO)
VALUES('0654123','34567','AFREEN',21,'FEMALE','LOWER',1,'OTHERS','VOTER ID','AD242FDGD');
insert into PASSENGER (PASS_ID,BOOKING_ID,PASS_NAME,AGE,GENDER,BERTH,SENIOR_CITIZEN,NATIONALITY,ID_CARD,ID_NO)
VALUES('65432','34567','AFREEN',21,'FEMALE','LOWER',1,'OTHERS','VOTER ID','VF42FDGD');
insert into PASSENGER (PASS_ID,BOOKING_ID,PASS_NAME,AGE,GENDER,BERTH,SENIOR_CITIZEN,NATIONALITY,ID_CARD,ID_NO)
VALUES('432','34567','SHAMIRA',26,'FEMALE','MIDDLE',1,'INDIAN','AADHAR','VGD');


DROP TABLE PASSENGER

CREATE PROCEDURE [dbo].[PASS_STORE]
(
@PASS_ID INT,
@NAME varchar(20),
@AGE INT,
@GENDER VARCHAR(20),
@BERTH varchar(20),
@CITIZEN VARCHAR(3),
@NATION VARCHAR(20),
@ID_CARD VARCHAR(20),
@ID_NO  VARCHAR(20),
@statement varchar(20)='')

AS
BEGIN
IF @statement='INSERT'
	BEGIN
	INSERT INTO PASSENGER(PASS_ID,PASS_NAME,AGE,GENDER,BERTH,SENIOR_CITIZEN,NATIONALITY,ID_CARD,ID_NO)
	VALUES(@PASS_ID,@NAME,@AGE,@GENDER,@BERTH,@CITIZEN,@NATION,@ID_CARD,@ID_NO);
	END
ELSE IF @statement='LIST'
	BEGIN
	SELECT * FROM PASSENGER
	END
ELSE IF @statement='UPDATE'
	BEGIN
	UPDATE PASSENGER SET BERTH=@BERTH WHERE PASS_ID=@PASS_ID
	END
END; 


CREATE PROCEDURE PASS_DEL_SEL
(
@PASS_ID INT,
@STATEMENT VARCHAR(10)='')
AS
BEGIN
IF @STATEMENT='DELETE'
	BEGIN
	DELETE FROM PASSENGER WHERE PASS_ID=@PASS_ID
	END
ELSE IF @STATEMENT='SELECT'
	BEGIN
	SELECT * FROM PASSENGER WHERE PASS_ID=@PASS_ID
	END
END;

EXEC PASS_STORE 1001,'ALI',20,'MALE','LOWER','NO','INDIAN','AADHAR','1EEegRDF','INSERT'
EXEC PASS_DEL_SEL 1001,'DELETE'
SELECT * FROM PASSENGER

use IRCTC;
DROP TABLE BERTH;
CREATE TABLE BERTH(BID VARCHAR(50) ,
BERTHTYPE VARCHAR(100) PRIMARY KEY,
CREATED_BY VARCHAR(50) DEFAULT 'AFREEN',
CREATED_DATETIME DATETIME DEFAULT GETDATE(),
MODIFIED_BY VARCHAR(50) NOT NULL DEFAULT 'ADMIN',
MODIFIED_DATETIME DATETIME NOT NULL DEFAULT GETDATE(),
ROWGUID VARCHAR(MAX) DEFAULT NEWID());

insert into berth(BID,BERTHTYPE) values('BID01','LOWER')
insert into berth(BID,BERTHTYPE) values('BID02','MIDDLE')
insert into berth(BID,BERTHTYPE) values('BID03','UPPER')


CREATE TABLE NATIONALITY(NID VARCHAR(50)  ,
NATION VARCHAR(100) PRIMARY KEY,
CREATED_BY VARCHAR(50) DEFAULT 'AFREEN',
CREATED_DATETIME DATETIME DEFAULT GETDATE(),
MODIFIED_BY VARCHAR(50) NOT NULL DEFAULT 'ADMIN',
MODIFIED_DATETIME DATETIME NOT NULL DEFAULT GETDATE(),
ROWGUID VARCHAR(MAX) DEFAULT NEWID());

insert into NATIONALITY(NID,NATION) values('NID01','INDIAN')
insert into NATIONALITY(NID,NATION) values('NID02','OTHERS')


CREATE TABLE ID_CARD_TYPE(CARD_TNO VARCHAR(50)  ,
ID_CARD VARCHAR(100) PRIMARY KEY,
CREATED_BY VARCHAR(50) DEFAULT 'AFREEN',
CREATED_DATETIME DATETIME DEFAULT GETDATE(),
MODIFIED_BY VARCHAR(50) NOT NULL DEFAULT 'ADMIN',
MODIFIED_DATETIME DATETIME NOT NULL DEFAULT GETDATE(),
ROWGUID VARCHAR(MAX) DEFAULT NEWID());

insert into ID_CARD_TYPE(CARD_TNO,ID_CARD) values('IDT01','AADHAR')
insert into ID_CARD_TYPE(CARD_TNO,ID_CARD) values('IDT02','LICENSE')
insert into ID_CARD_TYPE(CARD_TNO,ID_CARD) values('IDT03','VOTER ID')

DROP TABLE NATIONALITY;
 DROP TABLE ID_CARD_TYPE;

 SELECT * FROM BERTH;
  SELECT * FROM NATIONALITY;
  SELECT * FROM ID_CARD_TYPE;

